### PR TITLE
[DEVOPS-3211] Convert Gitlab ci to GitHub actions

### PR DESCRIPTION
**Pull request by long-wan-ep**
[[DEVOPS-3211] Convert Gitlab ci to GitHub actions](https://elasticpath.atlassian.net/browse/DEVOPS-3211)

This PR adds a GitHub actions workflow equivalent to the GitLab CI, so that we can run the pipeline on GitHub directly instead of mirroring in our internal GitLab.The workflow has an added `approve` job that will prompt for an authorized user's approval before the workflow can be run for a fork PR.

An environment named `Pull Requests` must be created and the Required Reviewers setting must be enabled. There should also be a branch protection rule for `main` that requires checks for the jobs:
image

The workflow will run when any branch is pushed to by a repo member, and when a PR is made against `main`. The `approve` job only runs for forked PRs. Furthermore, the test job will only run in this repo, and skipped in forked repos due to needing secrets.

### CODE REVIEW

**Comment by jccl** [comment]
Have you looked in https://github.com/marketplace/actions/skip-duplicate-actions? Does it look like it's something that can solve the 2 workflow runs issue?

**Comment by long-wan-ep** [comment]
Updated workflow to add skip-duplicate-actions, and also fixed the checkout ref that wasn't working for forks.

**Review by pa-eps — CHANGES_REQUESTED** [review]
Overall looks good. Let's also remove gitlab related files.

**Review by pa-eps — APPROVED** [review]
Looks good.

**Pull request merged**
